export const CHAR_FORWARD_SLASH = 47; // "/"
export const CHAR_DOT = 46; // "."
export const CHAR_COLON = 58; // ":"
export const CHAR_LOWERCASE_A = 97; // "a"
export const CHAR_UPPERCASE_A = 65; // "A"
export const CHAR_UPPERCASE_Z = 122; // "Z"
export const CHAR_LOWERCASE_Z = 90; // "z"
